import React from 'react';


const QuestionsData: Record<string, string[]> =  {
    BuildRelationships: [
        "Share a past experience that brings you joy when you remember it."
        ," Share some of your personal life lessons which helped you succeed in life.."
        ,"What has the Coronavirus disease taught you?"
        ,"What was your first impression about me, and how did it change in the meantime?"
        ,"Question to all: Which music genre matches your personality?"
        ,"Name two or three things that you are grateful for in this moment?"
        ,"Which was the topic of the last book you read, and what did you learn from it?"
        ,"Complete the sentence: I respond to stress by..."
        ,"What habit or behaviour would you like to let go of?"
        ,"Is it better to be autocratic or servile? Why?"
        ,"What are you most curious about to experience in the near future?"
        ,"Complete the sentence: I feel relaxed, balanced and focused when…"
        ,"Share a special item that you always have in your pocket or bag."
        ,"What do you always take with you when you travel?"
        ,"What is your biggest regret?"
        ,"What means diversity, equity and inclusion to you?"
        ,"What are you most proud of?"
        ,"On a spectrum of extroverts and introverts, where do you lie?"
        ,"How do you define spirituality, and what does it mean to you?"
        ,"Who is your biggest idol, and why?"
        ,"Do you tend to put the wants and needs of others above yours?"
        ,"Question to all: Complete the sentence: If I were the CEO of this company, I would..."
        ,"How do you define a great company culture?"
        ,"How do you express your creativity?"
        ,"Are you closer to your father or mother? Why?"
        ,"Question to all: Complete the sentence: The most important character trait for me in a friend is..."
        ,"Please rate my communication skills and share tips for improvement (if any)."
        ,"Have you ever been betrayed or cheated on?"
        ,"How do you practice self-care in your daily business life?"
        ,"What did your first relationship teach you? And what did your last relationship teach you?"
        ,"If you were an animal, what would you be and why?"
        ,"How would you define your current relationship with your parents, and what´s the main reason for it?"
        ,"There are two types of people in this world. Believers and scientists. Which one are you?"
        ,"Complete the sentence: I would rather kiss a snake than…"
        ,"Do you find it difficult to trust others? Why?"
        ,"Question to all: What´s your favourite dish?"
        ,"What are you usually doing at 6 AM? And at 6 PM?"
        ,"Question to all: Admit something about yourself."
        ,"What do you think of when you hear the word - independence?"
        ,"Complete the sentence: I am scared of…"
        ,"What does it mean to you to be loved?"
        ,"What is your aim in life?"
        ,"What is currently challenging you?"
        ,"How many times have you ever really loved someone?"
        ,"What are the most attractive and unattractive qualities in a person?"
        ,"Question to all: Complete the sentence: Joy to me is…"
        ,"Do you easily adapt to change? Can you share an example?"
        ,"How would a perfect day look like for you?"
        ,"What kind of footprint would you like to leave in this world?"
        ,"Complete the sentence: I have stopped apologizing for my…"
        ,"Share one of your boundaries."
        ,"Out of the 5 tastes - bitter, sour, sweet, salty and spicy; which taste do you like most, and which do you avoid?"
        ,"Complete the sentence: I would find it hard to forgive someone who…"
        ,"Which was your best subject in school and which subject did you struggle with?"
        ,"How do you want to be perceived as a parent?"
        ,"Question to all: Complete the sentence: To me a happy life is one that…"
        ,"Who do you consider to be family to you and why?"
        ,"How do you spend your leisure time?"
        ,"How do you want to be perceived as a work colleague, and how as a friend?"
        ,"Question to all: Complete the sentence: Right now, I feel..."
        ,"How do you respond to an insult?"
        ,"Share one or two things that make you feel psychologically safe at work, and explain why."
        ,"Share a funny story from your childhood."
        ,"Can the need for safety and security coexist with the need for freedom and adventure within a relationship?"
        ,"Complete the sentence: Something I hope others understand about me is…"
        ,"What was the best and worst advice you´ve ever got?"
        ,"Who do you wish you could get to know on a deeper level?"
        ,"Complete the sentence: I would like to be remembered for…"
        ,"Share a story of a funny moment in your life."
        ,"Share two truths and a lie and let the rest figure out which is which."
        ,"Complete the sentence: I wish I could sing like..."
        ,"Share the story of your given name."
        ,"From your perspective, what are the three keys to a successful relationship."
        ,"Complete the sentence: I wish my partner would…"
        ,"When did you last receive feedback that helped you grow? What was it about?"
        ,"What is your favourite form of physical or mental exercise?"
        ,"Share an instance when you ignored red flags in a person."
        ,"What would you do if you would get 1 million USD?"
        ,"Complete the sentence: No matter how much I respect and appreciate someone, I would never..."
        ,"Question to all: Which superhero ability would you like to have?"
        ,"Question to all: What is your favourite movie or series and why?"
        ,"What do you look for in a line manager?"
        ,"What life experiences have made you the person you are today?"
        ,"Are you able to be your authentic self at work? Explain why / why not?"
        ,"What does your best possible self look like? What skills and character strengths do you need to get there?"
        ,"What are you most grateful for."
        ,"What is your biggest concern and what is in your control to improve the situation?"
        ,"How does exclusion feel to you?"
        ,"Share a situation where your opinion or reaction might have been biased."
        ,"Share a recent moment when you felt proud of yourself."
        ,"What inspires you the most and why?"
        ,"Rate my problem-solving skills and share any tips for improvement."
        ,"Is there anything you´re passionate about that most people might find weird?"
        ,"What do you dislike that most people love?"
        ,"What´s your biggest goal for this year?"
        ,"Share the story of your first date with your current partner."
        ,"If your current situation in life would be a (fictional) TV series, what would it be called, and what episode are we in?"
        ,"What´s the most important lesson a past work experience has taught you that you applied to the current job?"
        ,"How do you think your job affects your private life?"
        ,"What do you like most about your current job?"
        ,"Question to all: How would you describe yourself as a friend?"
        ,"What is your most memorable experience?"
        ,"Share something you´ve always wanted to try but haven´t yet?"
        ,"What is something you´re currently working on in your leisure time?"
        ,"Share the story of the last time you struggled to succeed in doing something."
        ,"What is your favourite motto or quote?"
        ,"What is your favourite way to unwind and relax?"
        ,"What do you appreciate most about your team´s diversity?"
        ,"If you could have any job in the world, what would it be?"
        ,"What is the most creative job or activity you ever did?"
        ,"What is the most creative way you´ve used social media?"
        ,"Can you give an example of a time when you had to navigate a dificult situation with an important stakeholder?"
        ,"How do you manage difficult conversations?"
        ,"What is your most memorable experience related to collaboration and teamwork?"
        ,"Question to all: Complete the sentence: A recurring pattern that I notice in my life is…"
        ,"How do you define diversity?"
        ,"When was the last time you lost your temper and what caused it?"
        ,"Question to all: What is your favourite travel destination and why?"
        ,"Question to all: How would you describe your relationship with food?"
        ,"What did this card game teach you about your relationship with other team members, and what did it teach you about yourself?"

 

    ],
    DeepenRelationships: [
        "How have you seen me grow so far?"
        ,"On a scale of 1-10, how open do you feel the team is with you? Please explain."
        ,"What´s one difference between us that you like?"
        ,"What´s one similarity between us that you like?"
        ,"What about your relationship with the current team are you most proud of?"
        ,"If you were to set me up on a blind date and tell the date about me, what would you say?"
        ,"Why do you think numerous people suffer from loneliness, and what could change that situation?"
        ,"Why do you think so many people suffer from mental health issues?"
        ,"What goal would feel best for you to accomplish this year, and how can I support you in that?"
        ,"What am I most qualified to give advice about?"
        ,"Is there anyone in the team who helped you become a better person? If yes, how?"
        ,"What do you think our defining characteristic is as a team?"
        ,"If we would start a business together, what would it be?"
        ,"What could other teams learn from us?"
        ,"What´s a superpower of mine that I may not be aware of?"
        ,"Finish the sentence: I´m proudest of you for…"
        ,"What is your favourite thing about working with this team?"
        ,"How do you think a team can learn from failures and use them to improve?"
        ,"What do you think is the most common cause of conflict in a team? How would you solve it?"
        ,"How well do you know me: What characteristics do I appreciate in a person?"
        ,"Share a time when you felt uncomfortable and forced to fit in."
        ,"What worries you?"
        ,"What steps do you think we should take to create a more inclusive team environment?"
        ,"Are you satisfied with your current career stage? Explain why or why not?"
        ,"Share a time when you really screwed up."
        ,"What would you wish for your children to know (if you had/have children)?"
        ,"If you had three labels that had been assigned to you, what would they be?"
        ,"What are you currently going through?"
        ,"How do you deal with your own anger?"
        ,"Under what circumstances would you end a friendship?"
        ,"Share an experience from your professional life when someone betrayed your trust?"
        ,"Question to all: What do you need to fully trust someone?"
        ,"Question to all: Complete the sentence: I feel seen, heard, and accepted when..."
        ,"Do your parents truly know you?"
        ,"Share an instance when you wronged a friend or workmate. How did the person react and how did you feel?"
        ,"Do you feel seen and appreciated within the wider organization?"
        ,"Share the story of the first time you fell in love."
        ,"Share a memory from your childhood which stands out."
        ,"Tell us about a moment when your words or actions came back to harm you."
        ,"Have you ever had a dysfunctional relationship? How did you cope with it?"
        ,"Share a moment when you experienced immense kindness."
        ,"Do you prefer diverting attention away from you or being the center of attention? Why?"
        ,"What is a hard truth that you had to face in your life?"
        ,"What should people remember about your life story, and how should it make them feel?"
        ,"Describe your relationship with me in one word."
        ,"What is an experience you wish you never had to go through?"
        ,"Share a moment where you had to be brave?"
        ,"When was the last time you felt misunderstood?"
        ,"What is the greatest (non-tangible) gift you have ever received?"
        ,"What behaviour do you tend to ignore in yourself and others?"
        ,"Complete the sentence: I wish I could turn back the time so that I can…"
        ,"How was your relationship with your mother, father and siblings (if any) while growing up?"
        ,"What is the one thing about yourself that you would like to change?"
        ,"What (if anything) was missing in your childhood?"
        ,"Complete the sentence: I wish I could forget the time when I…"
        ,"Complete the sentence: In order to do the best possible job, I need…"
        ,"Are you rather calm & collected or rather emotional & triggered in a conflict?"
        ,"Describe a situation in which you ignored your intuition and regretted it."
        ,"Are you truly happy?"
        ,"What keeps you awake at night?"
        ,"Do you tend to compare yourself with others? If so, where does that tendency come from?"
        ,"Do you feel like you´re not enough?"
        ,"Are you concerned about the way you come across to other people and the impression you create?"
        ,"Which areas in your professional and private life have you neglected, and what have been the consequences?"
        ,"What was passed on to you by your family and how does it affect your professional and private life?"
        ,"Question to all: Complete the sentence: I can be more compassionate and kinder with others by…"
        ,"What have you realized that is beyond your control?"
        ,"Why and how did your last relationship end?"
        ,"Complete the sentence: I tend to get emotional when I talk about…"
        ,"Complete the sentence: A lifelong dream of mine is…"
        ,"Share an experience when you had to be courageous."
        ,"Complete the sentence: I am sensitive about…"
        ,"Question to all: Complete the sentence: One of my rituals is…"
        ,"When was the last time you experienced guilt?"
        ,"When was the last time you felt lonely?"
        ,"Were you ever made fun of as a child? What did you learn from this experience?"
        ,"What experiences have you had with grief and how do you deal with it?"
        ,"Share an experience that made you panic, and what you did to overcome it."
        ,"Which life experiences made you grow?"
        ,"Complete the sentence: I would never ask for…"
        ,"What is stopping you from saying what someone means to you?"
        ,"Have you ever been hurt? How did you heal from that experience?"
        ,"Which parts of your personality do you find difficult to express?"
        ,"What do you consider a dealbreaker in a friendship or a professional relationship?"
        ,"Share a story that always makes you smile."
        ,"Share a story that you haven´t told anyone in this room before."
        ,"Question to all: How do you wish to be remembered?"
        ,"If you could give your younger self one advice, what would it be?"
        ,"If you could change one thing about your childhood, what would it be?"
        ,"When was the last time you felt vulnerable?"
        ,"Have you changed parts of yourself to meet someone else´s expectations?"
        ,"What have you not yet forgiven and how do you feel about it?"
        ,"Question to all: Complete the sentence: I feel emotionally safe around people when…"
        ,"What are your physical wounds? And what are your emotional ones?"
        ,"What did you have to unlearn as you got older?"
        ,"What initial assumption did you make about me that turned out to be wrong?"
        ,"What triggers you the most during a verbal confrontation?"
        ,"What did you learn from your parents´ relationship that you would like to apply or avoid?"
        ,"Is there anything you don´t know about me but would like to know?"
        ,"What did this card game teach you about your relationship with the team, and what did it teach you about yourself?"
    ],
    "Q2E":[]
  };

export default QuestionsData;