import React from 'react';


const QuestionsData: Record<string, string[]> =  {
    BuildRelationships: [
        "Share a past experience that feels like a warm hug and brings you comfort when you remember it."
        ,"Question to all: Complete the sentence: In a crowd of people, I am the ….... one."
        ,"What has Covid 19 taught you?"
        ,"Why do you think so many of us suffer from loneliness?"
        ,"What was the first thing you noticed about me?"
        ,"Question to all: Which music genre matches your personality?"
        ,"What are the three things that you are grateful for in this moment?"
        ,"Which was the last book you read, what was it about and what did you take from it?"
        ,"Complete the sentence: I respond to stress by..."
        ,"What habit do you need to let go of?"
        ,"Is it better to be autocratic or servile? Why?"
        ,"What are you most curious about?"
        ,"Complete the sentence: I feel relaxed, centered and grounded when…"
        ,"Share an item that is always in your bag or pocket."
        ,"What do you always do before getting on a flight?"
        ,"What is your biggest regret?"
        ,"What means diversity, equity and inclusion to you?"
        ,"What are you most proud of?"
        ,"On a spectrum of introverts and extroverts, where do you lie?"
        ,"What does spirituality mean to you?"
        ,"Who is your biggest idol, and why?"
        ,"Do you tend to put the wants and needs of others first?"
        ,"Complete the sentence: I would never.."
        ,"What does culture mean to you?"
        ,"Do you consider yourself creative? If so, how do you express your creativity?"
        ,"Are you closer to your mother or father? Why?"
        ,"What would you like to let go of?"
        ,"Complete the sentence: The most important trait for me in a partner is..."
    ],
    DeepenRelationships: [
        "If you were to set me up on a blind date and tell the date about me, what would you say?"
        ,"How well do you know me: What characteristics do I appreciate in a person?"
        ,"Share a time when you felt pressured to fit in."
        ,"When was the last time you lost your temper and what caused it?"
        ,"What worries you?"
        ,"Are you satisfied with where you are in your career - why or why not?"
        ,"Share a moment when you really screwed up."
        ,"If you had/have children, what would you wish for them to know?"
        ,"If you had three labels that had been assigned to you, what would they be?"
        ,"What are you currently going through?"
        ,"How do you manage your own anger?"
        ,"Could you forgive your partner if he/she cheated on you?"
        ,"Question to all: What do you need to fully trust someone?"
        ,"Question to all: Complete the sentence: I feel seen, heard, and accepted when..."
        ,"Do your parents truly know you?"
        ,"Share the story of the last time you cried."
        ,"Share an instance when you wronged someone. How did the person react and how did you respond?"
        ,"Do you feel seen and loved within your social circle?"
        ,"Share the story of the first time you fell in love."
        ,"Question to all: How would you describe your relationship with food?"
        ,"Share a memory from your childhood which stands out."
        ,"Describe a time when your words or actions came back to harm you."
        ,"Have you ever had a dysfunctional relationship? How did you cope with it?"
        ,"Share a moment when you received immense kindness."
        ,"Do you prefer being at the center of attention or diverting attention away from you? Why?"
        ,"What steps do you think we should take to create a more inclusive team environment?"
    ],
    "Q2E":[]
  };

export default QuestionsData;